-- c.lua — single-file language plugin.
-- Manifest fields (name, version, ...) live at the top level of the
-- returned table, same as before; init/unload replace what used to be
-- a separate init.lua, and the syntax.add{} body replaces impl.lua.
return {
  name = "c",
  version = "0.1.0",
  description = "C language syntax support",
  author = "cdin Team",
  license = "MIT",
  category = "languages",
  type = "plugin",
  essential = false,
  dependencies = {  },
  min_cdin_version = "0.5.0",
  tags = { "language", "c" },
  init = function(core, config)
    local syntax = require "core.syntax"

    syntax.add {
      files = { "%.c$", "%.h$", "%.inl$", "%.cpp$", "%.hpp$" },
      comment = "//",
      patterns = {
        { pattern = "//.-\n",               type = "comment"  },
        { pattern = { "/%*", "%*/" },       type = "comment"  },
        { pattern = { "#", "[^\\]\n" },     type = "comment"  },
        { pattern = { '"', '"', '\\' },     type = "string"   },
        { pattern = { "'", "'", '\\' },     type = "string"   },
        { pattern = "-?0x%x+",              type = "number"   },
        { pattern = "-?%d+[%d%.eE]*f?",     type = "number"   },
        { pattern = "-?%.?%d+f?",           type = "number"   },
        { pattern = "[%+%-=/%*%^%%<>!~|&]", type = "operator" },
        { pattern = "[%a_][%w_]*%f[(]",     type = "function" },
        { pattern = "[%a_][%w_]*",          type = "symbol"   },
      },
      symbols = {
        ["if"]       = "keyword",
        ["then"]     = "keyword",
        ["else"]     = "keyword",
        ["elseif"]   = "keyword",
        ["do"]       = "keyword",
        ["while"]    = "keyword",
        ["for"]      = "keyword",
        ["break"]    = "keyword",
        ["continue"] = "keyword",
        ["return"]   = "keyword",
        ["goto"]     = "keyword",
        ["struct"]   = "keyword",
        ["union"]    = "keyword",
        ["typedef"]  = "keyword",
        ["enum"]     = "keyword",
        ["extern"]   = "keyword",
        ["static"]   = "keyword",
        ["volatile"] = "keyword",
        ["const"]    = "keyword",
        ["inline"]   = "keyword",
        ["switch"]   = "keyword",
        ["case"]     = "keyword",
        ["default"]  = "keyword",
        ["auto"]     = "keyword",
        ["const"]    = "keyword",
        ["void"]     = "keyword",
        ["int"]      = "keyword2",
        ["short"]    = "keyword2",
        ["long"]     = "keyword2",
        ["float"]    = "keyword2",
        ["double"]   = "keyword2",
        ["char"]     = "keyword2",
        ["unsigned"] = "keyword2",
        ["bool"]     = "keyword2",
        ["true"]     = "literal",
        ["false"]    = "literal",
        ["NULL"]     = "literal",
      },
    }
  end,

  unload = function() end,
}
