-- Generated catalog index - do not edit by hand; run
-- `lua scripts/generate-manifest.lua` instead.
--
-- Every plugin carries its manifest inline: in init.lua for a
-- directory plugin, in the returned table for a single-file one or a
-- theme. There is no separate manifest.lua.
--
-- `files` on every entry lists that entry's files relative to the repo
-- root, so callers can fetch them individually without cloning.
return {
  core_files = {
    "cdinx/README.md",
    "cdinx/command.lua",
    "cdinx/config.lua",
    "cdinx/init.lua",
    "cdinx/manager/catalog.lua",
    "cdinx/manager/deps.lua",
    "cdinx/manager/init.lua",
    "cdinx/manager/lifecycle.lua",
    "cdinx/manager/registry.lua",
    "cdinx/manager/runtime.lua",
    "cdinx/manager/state.lua",
    "cdinx/manager/util.lua",
    "cdinx/manifest.lua",
    "cdinx/panel.lua",
  },
  plugins = {
    ["autocomplete"] = {
      category = "core",
      type = "plugin",
      version = "0.2.0",
      description = "Symbol-based completion popup for open documents, extensible with providers",
      essential = false,
      files = {
        "X/core/autocomplete/README.md",
        "X/core/autocomplete/api.lua",
        "X/core/autocomplete/commands.lua",
        "X/core/autocomplete/init.lua",
        "X/core/autocomplete/keymap.lua",
        "X/core/autocomplete/popup.lua",
        "X/core/autocomplete/source.lua",
        "X/core/autocomplete/suggest.lua",
      },
    },
    ["autoreload"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Reload files changed outside CDIN",
      essential = false,
      files = {
        "X/core/autoreload.lua",
      },
    },
    ["autoupdate"] = {
      category = "core",
      type = "plugin",
      version = "0.2.0",
      description = "Check CDIN releases and offer updates",
      essential = false,
      files = {
        "X/core/autoupdate/README.md",
        "X/core/autoupdate/commands.lua",
        "X/core/autoupdate/impl.lua",
        "X/core/autoupdate/init.lua",
        "X/core/autoupdate/keymap.lua",
        "X/core/autoupdate/manager/fetcher.lua",
        "X/core/autoupdate/manager/utils.lua",
      },
    },
    ["c"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "C language syntax support",
      essential = false,
      files = {
        "X/syntax/c.lua",
      },
    },
    ["catppuccin-mocha"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: catppuccin-mocha",
      essential = false,
      files = {
        "X/themes/catppuccin-mocha/theme.lua",
      },
    },
    ["default"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: default",
      essential = true,
      files = {
        "X/themes/default/theme.lua",
      },
    },
    ["dracula"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: dracula",
      essential = false,
      files = {
        "X/themes/dracula/theme.lua",
      },
    },
    ["finder"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Find a file by name, open a file or folder by path",
      essential = false,
      files = {
        "X/core/finder/README.md",
        "X/core/finder/init.lua",
      },
    },
    ["git"] = {
      category = "core",
      type = "plugin",
      version = "0.2.0",
      description = "Git status, ignore rules and shared shell recipes",
      essential = false,
      files = {
        "X/core/git/README.md",
        "X/core/git/api.lua",
        "X/core/git/exec.lua",
        "X/core/git/init.lua",
        "X/core/git/manager/find-git.lua",
        "X/core/git/manager/ops.lua",
        "X/core/git/manager/utils.lua",
        "X/core/git/recipes.lua",
        "X/core/git/status.lua",
      },
    },
    ["git-treeview"] = {
      category = "integration",
      type = "plugin",
      version = "0.2.0",
      description = "Git status badges and refresh integration for Treeview",
      essential = false,
      files = {
        "X/integration/git-treeview/init.lua",
      },
    },
    ["github-light"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: github-light",
      essential = false,
      files = {
        "X/themes/github-light/theme.lua",
      },
    },
    ["gruvbox-dark"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: gruvbox-dark",
      essential = false,
      files = {
        "X/themes/gruvbox-dark/theme.lua",
      },
    },
    ["javascript"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "JavaScript syntax support",
      essential = false,
      files = {
        "X/syntax/javascript.lua",
      },
    },
    ["lua"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "Lua syntax support",
      essential = false,
      files = {
        "X/syntax/lua.lua",
      },
    },
    ["markdown"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "Markdown syntax support",
      essential = false,
      files = {
        "X/syntax/markdown.lua",
      },
    },
    ["menu"] = {
      category = "core",
      type = "plugin",
      version = "0.2.0",
      description = "Generic searchable menu that features extend with their own sections",
      essential = false,
      files = {
        "X/core/menu/README.md",
        "X/core/menu/impl.lua",
        "X/core/menu/init.lua",
      },
    },
    ["modules"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Reload a loaded module, open the user or project config module",
      essential = false,
      files = {
        "X/core/modules/README.md",
        "X/core/modules/init.lua",
      },
    },
    ["monokai"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: monokai",
      essential = false,
      files = {
        "X/themes/monokai/theme.lua",
      },
    },
    ["nord"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: nord",
      essential = false,
      files = {
        "X/themes/nord/theme.lua",
      },
    },
    ["palette"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Command palette: run any command by name",
      essential = false,
      files = {
        "X/core/palette/README.md",
        "X/core/palette/init.lua",
      },
    },
    ["python"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "Python syntax support",
      essential = false,
      files = {
        "X/syntax/python.lua",
      },
    },
    ["rtl_toggle"] = {
      category = "optional",
      type = "plugin",
      version = "0.2.0",
      description = "Toggle RTL text direction and Arabic shaping",
      essential = false,
      files = {
        "X/optional/rtl_toggle/README.md",
        "X/optional/rtl_toggle/impl.lua",
        "X/optional/rtl_toggle/init.lua",
      },
    },
    ["search"] = {
      category = "core",
      type = "plugin",
      version = "0.2.0",
      description = "Document search/replace and project-wide search",
      essential = false,
      files = {
        "X/core/search/README.md",
        "X/core/search/buffer.lua",
        "X/core/search/commands.lua",
        "X/core/search/init.lua",
        "X/core/search/keymap.lua",
        "X/core/search/manager/init.lua",
        "X/core/search/project.lua",
      },
    },
    ["session"] = {
      category = "core",
      type = "plugin",
      version = "0.2.0",
      description = "Persistent session restore for buffers and project state",
      essential = false,
      files = {
        "X/core/session/README.md",
        "X/core/session/api.lua",
        "X/core/session/commands.lua",
        "X/core/session/init.lua",
        "X/core/session/keymap.lua",
        "X/core/session/manager/session-loader.lua",
        "X/core/session/manager/sys.lua",
      },
    },
    ["session-theme-switcher"] = {
      category = "integration",
      type = "plugin",
      version = "0.1.0",
      description = "Persist the theme chosen with the theme switcher into the session",
      essential = false,
      files = {
        "X/integration/session/theme-switcher/init.lua",
      },
    },
    ["solarized-dark"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: solarized-dark",
      essential = false,
      files = {
        "X/themes/solarized-dark/theme.lua",
      },
    },
    ["solarized-light"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: solarized-light",
      essential = false,
      files = {
        "X/themes/solarized-light/theme.lua",
      },
    },
    ["tab"] = {
      category = "core",
      type = "plugin",
      version = "0.2.0",
      description = "Tab management and tab session support",
      essential = false,
      files = {
        "X/core/tab/README.md",
        "X/core/tab/commands.lua",
        "X/core/tab/impl.lua",
        "X/core/tab/init.lua",
        "X/core/tab/keymap.lua",
        "X/core/tab/manager.lua",
        "X/core/tab/manager/index.lua",
        "X/core/tab/manager/operation.lua",
      },
    },
    ["tab-session"] = {
      category = "integration",
      type = "plugin",
      version = "0.2.0",
      description = "Persist open tabs and restore them on the next run",
      essential = false,
      files = {
        "X/integration/tab-session/init.lua",
        "X/integration/tab-session/session.lua",
      },
    },
    ["theme_switcher"] = {
      category = "optional",
      type = "plugin",
      version = "0.2.0",
      description = "Switch between installed CDIN themes",
      essential = false,
      files = {
        "X/optional/theme_switcher/README.md",
        "X/optional/theme_switcher/impl.lua",
        "X/optional/theme_switcher/init.lua",
      },
    },
    ["tokyo-night"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: tokyo-night",
      essential = false,
      files = {
        "X/themes/tokyo-night/theme.lua",
      },
    },
    ["treeview"] = {
      category = "core",
      type = "plugin",
      version = "0.2.0",
      description = "File tree sidebar with navigation and filesystem actions",
      essential = false,
      files = {
        "X/core/treeview/README.md",
        "X/core/treeview/api.lua",
        "X/core/treeview/cache.lua",
        "X/core/treeview/commands.lua",
        "X/core/treeview/init.lua",
        "X/core/treeview/keymap.lua",
        "X/core/treeview/nav.lua",
        "X/core/treeview/readonly.lua",
        "X/core/treeview/tree/build.lua",
        "X/core/treeview/tree/operations.lua",
        "X/core/treeview/treeview_impl.lua",
      },
    },
    ["trimwhitespace"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Trim trailing whitespace on save",
      essential = false,
      files = {
        "X/core/trimwhitespace.lua",
      },
    },
    ["typescript"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "TypeScript syntax support",
      essential = false,
      files = {
        "X/syntax/typescript.lua",
      },
    },
    ["unicode_inspect"] = {
      category = "optional",
      type = "plugin",
      version = "0.2.0",
      description = "Show the codepoints of the selection or the character at the caret",
      essential = false,
      files = {
        "X/optional/unicode_inspect/README.md",
        "X/optional/unicode_inspect/impl.lua",
        "X/optional/unicode_inspect/init.lua",
      },
    },
    ["vim"] = {
      category = "core",
      type = "plugin",
      version = "0.2.0",
      description = "Vim-style modal editing and command-line integration",
      essential = true,
      files = {
        "X/core/vim/README.md",
        "X/core/vim/api.lua",
        "X/core/vim/commands.lua",
        "X/core/vim/ex/commandline.lua",
        "X/core/vim/ex/commands.lua",
        "X/core/vim/ex/fsops.lua",
        "X/core/vim/ex/help.lua",
        "X/core/vim/ex/history.lua",
        "X/core/vim/ex/init.lua",
        "X/core/vim/ex/suggest.lua",
        "X/core/vim/ex/tokenize.lua",
        "X/core/vim/init.lua",
        "X/core/vim/keymap.lua",
        "X/core/vim/registry.lua",
        "X/core/vim/shell/commands.lua",
        "X/core/vim/shell/init.lua",
        "X/core/vim/shell/keymap.lua",
        "X/core/vim/vimode/init.lua",
        "X/core/vim/vimode/keys.lua",
        "X/core/vim/vimode/mode.lua",
        "X/core/vim/vimode/motions.lua",
        "X/core/vim/vimode/status.lua",
      },
    },
    ["vim-git"] = {
      category = "integration",
      type = "plugin",
      version = "0.2.0",
      description = "Git commands and Git menu entries for Vim mode",
      essential = false,
      files = {
        "X/integration/vim/vim-git/commands.lua",
        "X/integration/vim/vim-git/init.lua",
        "X/integration/vim/vim-git/menu.lua",
      },
    },
    ["vim-menu"] = {
      category = "integration",
      type = "plugin",
      version = "0.2.0",
      description = "Vim file, shell and build menu built on the generic menu core",
      essential = false,
      files = {
        "X/integration/vim/vim-menu/commands.lua",
        "X/integration/vim/vim-menu/files.lua",
        "X/integration/vim/vim-menu/init.lua",
        "X/integration/vim/vim-menu/keymap.lua",
        "X/integration/vim/vim-menu/menu.lua",
      },
    },
    ["vim-plugin-manager"] = {
      category = "integration",
      type = "plugin",
      version = "0.2.0",
      description = "Vim bindings for the CDIN-X extension manager",
      essential = false,
      files = {
        "X/integration/vim/vim-plugin-manager/init.lua",
        "X/integration/vim/vim-plugin-manager/keymap.lua",
      },
    },
    ["vim-search"] = {
      category = "integration",
      type = "plugin",
      version = "0.2.0",
      description = "Search and project-search bindings for Vim mode",
      essential = false,
      files = {
        "X/integration/vim/vim-search/init.lua",
        "X/integration/vim/vim-search/keymap.lua",
      },
    },
    ["vim-tab"] = {
      category = "integration",
      type = "plugin",
      version = "0.2.0",
      description = "Vim tab commands backed by the CDIN tab plugin",
      essential = false,
      files = {
        "X/integration/vim/vim-tab/commands.lua",
        "X/integration/vim/vim-tab/init.lua",
        "X/integration/vim/vim-tab/keymap.lua",
      },
    },
    ["vim-treeview"] = {
      category = "integration",
      type = "plugin",
      version = "0.2.0",
      description = "Treeview navigation and context integration for Vim",
      essential = false,
      files = {
        "X/integration/vim/vim-treeview/commands.lua",
        "X/integration/vim/vim-treeview/init.lua",
      },
    },
    ["vim-window"] = {
      category = "integration",
      type = "plugin",
      version = "0.2.0",
      description = "Vim window commands backed by the CDIN window plugin",
      essential = false,
      files = {
        "X/integration/vim/vim-window/commands.lua",
        "X/integration/vim/vim-window/init.lua",
        "X/integration/vim/vim-window/keymap.lua",
      },
    },
    ["window"] = {
      category = "core",
      type = "plugin",
      version = "0.2.0",
      description = "Window splits, focus and layout management",
      essential = false,
      files = {
        "X/core/window/README.md",
        "X/core/window/commands.lua",
        "X/core/window/init.lua",
        "X/core/window/keymap.lua",
        "X/core/window/manager.lua",
        "X/core/window/manager/context.lua",
        "X/core/window/manager/focus.lua",
        "X/core/window/manager/ops.lua",
        "X/core/window/manager/teardown.lua",
      },
    },
  },
}
