-- Generated catalog index. Multi-module plugins use manifest.lua
-- (inside their own directory); single-file plugins and themes carry
-- the same manifest fields inline in their one .lua file.
-- `files` on every entry lists that entry's files relative to the repo
-- root, so callers can fetch them individually without cloning.
return {
  core_files = {
    "core/command.lua",
    "core/config.lua",
    "core/init.lua",
    "core/manager/catalog.lua",
    "core/manager/deps.lua",
    "core/manager/git.lua",
    "core/manager/init.lua",
    "core/manager/lifecycle.lua",
    "core/manager/runtime.lua",
    "core/manager/state.lua",
    "core/manager/util.lua",
    "core/manifest.lua",
    "core/panel.lua",
    "core/preboot.lua",
  },
  plugins = {
    ["autocomplete"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Symbol-based completion popup for open documents",
      essential = false,
      files = {
        "X/autocomplete/autocomplete.lua",
      },
    },
    ["autoreload"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Reload files changed outside CDIN",
      essential = true,
      files = {
        "X/core/autoreload.lua",
      },
    },
    ["c"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "C language syntax support",
      essential = false,
      files = {
        "X/syntax/c.lua",
      },
    },
    ["catppuccin-mocha"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: catppuccin-mocha",
      essential = false,
      files = {
        "X/themes/catppuccin-mocha.lua",
      },
    },
    ["core"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "CDIN built-in core extensions",
      essential = true,
      files = {
        "X/core/core.lua",
      },
    },
    ["default"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: default",
      essential = true,
      files = {
        "X/themes/default.lua",
      },
    },
    ["dracula"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: dracula",
      essential = false,
      files = {
        "X/themes/dracula.lua",
      },
    },
    ["git"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Git status, branch/ahead-behind info, ignore filtering, and shell command shortcuts",
      essential = true,
      files = {
        "X/core/git/commands.lua",
        "X/core/git/exec.lua",
        "X/core/git/init.lua",
        "X/core/git/manager/find-git.lua",
        "X/core/git/manager/ops.lua",
        "X/core/git/manager/utils.lua",
        "X/core/git/manifest.lua",
        "X/core/git/status.lua",
      },
    },
    ["github-light"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: github-light",
      essential = false,
      files = {
        "X/themes/github-light.lua",
      },
    },
    ["gruvbox-dark"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: gruvbox-dark",
      essential = false,
      files = {
        "X/themes/gruvbox-dark.lua",
      },
    },
    ["javascript"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "JavaScript syntax support",
      essential = false,
      files = {
        "X/syntax/javascript.lua",
      },
    },
    ["lua"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "Lua syntax support",
      essential = false,
      files = {
        "X/syntax/lua.lua",
      },
    },
    ["markdown"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "Markdown syntax support",
      essential = false,
      files = {
        "X/syntax/markdown.lua",
      },
    },
    ["monokai"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: monokai",
      essential = false,
      files = {
        "X/themes/monokai.lua",
      },
    },
    ["nord"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: nord",
      essential = false,
      files = {
        "X/themes/nord.lua",
      },
    },
    ["projectsearch"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Search project files using ripgrep/find",
      essential = true,
      files = {
        "X/projectsearch/projectsearch.lua",
      },
    },
    ["python"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "Python syntax support",
      essential = false,
      files = {
        "X/syntax/python.lua",
      },
    },
    ["rtl_toggle"] = {
      category = "optional",
      type = "plugin",
      version = "0.1.0",
      description = "Toggle right-to-left text direction at runtime",
      essential = false,
      files = {
        "X/optional/rtl_toggle/README.md",
        "X/optional/rtl_toggle/impl.lua",
        "X/optional/rtl_toggle/init.lua",
        "X/optional/rtl_toggle/manifest.lua",
      },
    },
    ["solarized-dark"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: solarized-dark",
      essential = false,
      files = {
        "X/themes/solarized-dark.lua",
      },
    },
    ["solarized-light"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: solarized-light",
      essential = false,
      files = {
        "X/themes/solarized-light.lua",
      },
    },
    ["tab"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Tab management and tab session support",
      essential = true,
      files = {
        "X/core/tab/README.md",
        "X/core/tab/commands.lua",
        "X/core/tab/impl.lua",
        "X/core/tab/init.lua",
        "X/core/tab/keymap.lua",
        "X/core/tab/manager.lua",
        "X/core/tab/manager/index.lua",
        "X/core/tab/manager/operation.lua",
        "X/core/tab/session.lua",
      },
    },
    ["theme_switcher"] = {
      category = "optional",
      type = "plugin",
      version = "0.1.0",
      description = "Interactive theme selection and theme persistence",
      essential = false,
      files = {
        "X/optional/theme_switcher/README.md",
        "X/optional/theme_switcher/impl.lua",
        "X/optional/theme_switcher/init.lua",
        "X/optional/theme_switcher/manifest.lua",
      },
    },
    ["tokyo-night"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: tokyo-night",
      essential = false,
      files = {
        "X/themes/tokyo-night.lua",
      },
    },
    ["treeview"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "File tree sidebar with navigation, Git state and filesystem actions",
      essential = true,
      files = {
        "X/core/treeview/README.md",
        "X/core/treeview/cache.lua",
        "X/core/treeview/git.lua",
        "X/core/treeview/init.lua",
        "X/core/treeview/keymap.lua",
        "X/core/treeview/nav.lua",
        "X/core/treeview/tree/build.lua",
        "X/core/treeview/tree/operations.lua",
        "X/core/treeview/treeview_impl.lua",
      },
    },
    ["trimwhitespace"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Trim trailing whitespace on save",
      essential = true,
      files = {
        "X/core/trimwhitespace.lua",
      },
    },
    ["typescript"] = {
      category = "syntax",
      type = "plugin",
      version = "0.1.0",
      description = "TypeScript syntax support",
      essential = false,
      files = {
        "X/syntax/typescript.lua",
      },
    },
    ["unicode_inspect"] = {
      category = "optional",
      type = "plugin",
      version = "0.1.0",
      description = "Inspect Unicode code points around the caret",
      essential = false,
      files = {
        "X/optional/unicode_inspect/README.md",
        "X/optional/unicode_inspect/impl.lua",
        "X/optional/unicode_inspect/init.lua",
        "X/optional/unicode_inspect/manifest.lua",
      },
    },
    ["vim"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Vim-style modal editing, commands, file menu and shell integration",
      essential = true,
      files = {
        "X/core/vim/README.md",
        "X/core/vim/commands/tab.lua",
        "X/core/vim/commands/vim.lua",
        "X/core/vim/commands/vim.menu.lua",
        "X/core/vim/commands/vim.shell.lua",
        "X/core/vim/commands/window.lua",
        "X/core/vim/ex.lua",
        "X/core/vim/fmenu.lua",
        "X/core/vim/init.lua",
        "X/core/vim/menu/build.lua",
        "X/core/vim/menu/exec.lua",
        "X/core/vim/menu/fs.ops.lua",
        "X/core/vim/shell.lua",
        "X/core/vim/vimode.lua",
      },
    },
    ["window"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Window splits, focus and layout management",
      essential = true,
      files = {
        "X/core/window/README.md",
        "X/core/window/commands.lua",
        "X/core/window/init.lua",
        "X/core/window/keymap.lua",
        "X/core/window/manager.lua",
        "X/core/window/manager/focus.lua",
        "X/core/window/manager/ops.lua",
      },
    },
  },
}
