-- Generated catalog index. Plugins use manifest.lua; themes use theme.lua.
-- `files` on every entry lists that entry's files relative to the repo
-- root, so callers can fetch them individually without cloning.
return {
  core_files = {
    "core/command.lua",
    "core/config.lua",
    "core/init.lua",
    "core/manager.lua",
    "core/manifest.lua",
    "core/session_bootstrap.lua",
  },
  plugins = {
    ["autocomplete"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Symbol-based completion popup for open documents",
      essential = true,
      files = {
        "X/core/autocomplete/README.md",
        "X/core/autocomplete/impl.lua",
        "X/core/autocomplete/init.lua",
        "X/core/autocomplete/manifest.lua",
      },
    },
    ["autoreload"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Reload files changed outside CDIN",
      essential = true,
      files = {
        "X/core/autoreload/README.md",
        "X/core/autoreload/impl.lua",
        "X/core/autoreload/init.lua",
        "X/core/autoreload/manifest.lua",
      },
    },
    ["autoupdate"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Check CDIN releases and offer updates",
      essential = true,
      files = {
        "X/core/autoupdate/README.md",
        "X/core/autoupdate/impl.lua",
        "X/core/autoupdate/init.lua",
        "X/core/autoupdate/manifest.lua",
      },
    },
    ["c"] = {
      category = "languages",
      type = "plugin",
      version = "0.1.0",
      description = "C language syntax support",
      essential = false,
      files = {
        "X/languages/c/README.md",
        "X/languages/c/impl.lua",
        "X/languages/c/init.lua",
        "X/languages/c/manifest.lua",
      },
    },
    ["catppuccin-mocha"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: catppuccin-mocha",
      essential = false,
      files = {
        "X/themes/catppuccin-mocha/theme.lua",
      },
    },
    ["core"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "CDIN built-in core extensions",
      essential = true,
      files = {
        "X/core/core/README.md",
        "X/core/core/init.lua",
        "X/core/core/manifest.lua",
      },
    },
    ["default"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: default",
      essential = false,
      files = {
        "X/themes/default/theme.lua",
      },
    },
    ["dracula"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: dracula",
      essential = false,
      files = {
        "X/themes/dracula/theme.lua",
      },
    },
    ["github-light"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: github-light",
      essential = false,
      files = {
        "X/themes/github-light/theme.lua",
      },
    },
    ["gruvbox-dark"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: gruvbox-dark",
      essential = false,
      files = {
        "X/themes/gruvbox-dark/theme.lua",
      },
    },
    ["javascript"] = {
      category = "languages",
      type = "plugin",
      version = "0.1.0",
      description = "JavaScript syntax support",
      essential = false,
      files = {
        "X/languages/javascript/README.md",
        "X/languages/javascript/impl.lua",
        "X/languages/javascript/init.lua",
        "X/languages/javascript/manifest.lua",
      },
    },
    ["lua"] = {
      category = "languages",
      type = "plugin",
      version = "0.1.0",
      description = "Lua syntax support",
      essential = false,
      files = {
        "X/languages/lua/README.md",
        "X/languages/lua/impl.lua",
        "X/languages/lua/init.lua",
        "X/languages/lua/manifest.lua",
      },
    },
    ["markdown"] = {
      category = "languages",
      type = "plugin",
      version = "0.1.0",
      description = "Markdown syntax support",
      essential = false,
      files = {
        "X/languages/markdown/README.md",
        "X/languages/markdown/impl.lua",
        "X/languages/markdown/init.lua",
        "X/languages/markdown/manifest.lua",
      },
    },
    ["monokai"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: monokai",
      essential = false,
      files = {
        "X/themes/monokai/theme.lua",
      },
    },
    ["nord"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: nord",
      essential = false,
      files = {
        "X/themes/nord/theme.lua",
      },
    },
    ["projectsearch"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Search project files using ripgrep/find",
      essential = true,
      files = {
        "X/core/projectsearch/README.md",
        "X/core/projectsearch/impl.lua",
        "X/core/projectsearch/init.lua",
        "X/core/projectsearch/manifest.lua",
      },
    },
    ["python"] = {
      category = "languages",
      type = "plugin",
      version = "0.1.0",
      description = "Python syntax support",
      essential = false,
      files = {
        "X/languages/python/README.md",
        "X/languages/python/impl.lua",
        "X/languages/python/init.lua",
        "X/languages/python/manifest.lua",
      },
    },
    ["rtl_toggle"] = {
      category = "optional",
      type = "plugin",
      version = "0.1.0",
      description = "Toggle right-to-left text direction at runtime",
      essential = false,
      files = {
        "X/optional/rtl_toggle/README.md",
        "X/optional/rtl_toggle/impl.lua",
        "X/optional/rtl_toggle/init.lua",
        "X/optional/rtl_toggle/manifest.lua",
      },
    },
    ["session"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Persistent session restore for buffers and project state",
      essential = true,
      files = {
        "X/core/session/README.md",
        "X/core/session/impl.lua",
        "X/core/session/init.lua",
        "X/core/session/manifest.lua",
      },
    },
    ["solarized-dark"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: solarized-dark",
      essential = false,
      files = {
        "X/themes/solarized-dark/theme.lua",
      },
    },
    ["solarized-light"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: solarized-light",
      essential = false,
      files = {
        "X/themes/solarized-light/theme.lua",
      },
    },
    ["tab"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Tab management and tab session support",
      essential = true,
      files = {
        "X/core/tab/README.md",
        "X/core/tab/commands.lua",
        "X/core/tab/impl.lua",
        "X/core/tab/init.lua",
        "X/core/tab/manager.lua",
        "X/core/tab/manifest.lua",
        "X/core/tab/session.lua",
      },
    },
    ["theme_switcher"] = {
      category = "optional",
      type = "plugin",
      version = "0.1.0",
      description = "Interactive theme selection and theme persistence",
      essential = false,
      files = {
        "X/optional/theme_switcher/README.md",
        "X/optional/theme_switcher/impl.lua",
        "X/optional/theme_switcher/init.lua",
        "X/optional/theme_switcher/manifest.lua",
      },
    },
    ["tokyo-night"] = {
      category = "themes",
      type = "theme",
      version = "0.1.0",
      description = "Theme: tokyo-night",
      essential = false,
      files = {
        "X/themes/tokyo-night/theme.lua",
      },
    },
    ["treeview"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "File tree sidebar with navigation, Git state and filesystem actions",
      essential = true,
      files = {
        "X/core/treeview/README.md",
        "X/core/treeview/cache.lua",
        "X/core/treeview/git.lua",
        "X/core/treeview/init.lua",
        "X/core/treeview/manifest.lua",
        "X/core/treeview/nav.lua",
        "X/core/treeview/treeview_impl.lua",
      },
    },
    ["trimwhitespace"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Trim trailing whitespace on save",
      essential = true,
      files = {
        "X/core/trimwhitespace/README.md",
        "X/core/trimwhitespace/impl.lua",
        "X/core/trimwhitespace/init.lua",
        "X/core/trimwhitespace/manifest.lua",
      },
    },
    ["typescript"] = {
      category = "languages",
      type = "plugin",
      version = "0.1.0",
      description = "TypeScript syntax support",
      essential = false,
      files = {
        "X/languages/typescript/README.md",
        "X/languages/typescript/impl.lua",
        "X/languages/typescript/init.lua",
        "X/languages/typescript/manifest.lua",
      },
    },
    ["unicode_inspect"] = {
      category = "optional",
      type = "plugin",
      version = "0.1.0",
      description = "Inspect Unicode code points around the caret",
      essential = false,
      files = {
        "X/optional/unicode_inspect/README.md",
        "X/optional/unicode_inspect/impl.lua",
        "X/optional/unicode_inspect/init.lua",
        "X/optional/unicode_inspect/manifest.lua",
      },
    },
    ["vim"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Vim-style modal editing, commands, file menu and shell integration",
      essential = true,
      files = {
        "X/core/vim/README.md",
        "X/core/vim/ex.lua",
        "X/core/vim/fmenu.lua",
        "X/core/vim/init.lua",
        "X/core/vim/manifest.lua",
        "X/core/vim/shell.lua",
        "X/core/vim/vimode.lua",
      },
    },
    ["window"] = {
      category = "core",
      type = "plugin",
      version = "0.1.0",
      description = "Window splits, focus and layout management",
      essential = true,
      files = {
        "X/core/window/README.md",
        "X/core/window/commands.lua",
        "X/core/window/impl.lua",
        "X/core/window/init.lua",
        "X/core/window/manager.lua",
        "X/core/window/manifest.lua",
      },
    },
  },
}
